index:
  welcome_message: >
    Welcome! Dive into pioneering research on trustworthy, interpretable AI systems.
  personal_photo: "/assets/profile.jpeg"
  # image_credit: >
  #   Photo by [Photographer Name] / CC-BY
  news_highlight_color: 'is-info'
  personal_description: >
    I'm **Akshat Dubey**, a **Research Associate** at the [Robert Koch Institute](https://www.rki.de) and a **PhD candidate** at [Freie Universität Berlin](https://www.fu-berlin.de).  
    My research centers on **Explainable AI (XAI)**, with a strong focus on:
    <br>
    <li> 🔍 **Uncertainty Quantification in XAI** – designing embedding principled confidence estimates methods to assess and convey explanation confidence in applications like healthcare.
    <br>
    <li>🏥 **Healthcare XAI** – integrating explainable, uncertainty-aware ML into the workflows.
    <br>
    <li> 🧠 **Persona-Adaptable LLM Strategies** – methods to adapt large language models to user perspectives.
    <br>
    <li> ⚖️ **Regulatory-Compliant AI Design** – implementing frameworks (Nested Model for AI Design and Validation) aligned with EU AI regulations.
    <br>
    <li> 🎲 **Distributed Gaussian Process Learning** – elective/trust-based GP frameworks for decentralized decision-making.
    <br>
    <li> 🧠 **LLMs with LoRA/QLoRA & Quantization** – deploying quantized LLMs fine‑tuned with LoRA adapters to enable large-model utility on constrained hardware.  
    <br>
    <li> 🐳 **Docker & Orchestration Platforms** – automating reproducible ML pipelines for model training, deployment, and monitoring at scale.  
    <br>
    <li> 📈 **Mixed-Integer Linear Programming (MILP)** – optimizing structure of surrogate interpretable graphs from decision forests to maximize explainability via visual graphs.  
    <br>
    <li> 🤝 **Graph Neural Networks (GNNs)**, NLP, and Interactive Visualization – integrating human–computer interaction for trust‑building and exploration of AI decisions.
    <br>
    <br>
    <p>
    I am a "math nerd" who is also a "computational thinker" & "algorithm enthusiast", working under the supervision of **Dr habil. Georges Hattab**. Let’s collaborate—connect on [LinkedIn](https://www.linkedin.com/in/Akshat0007).
    </p>
  footnote: >
    Site crafted by [Akshat Dubey](https://github.com/dubeyakshat07) using [Jekyll](https://jekyllrb.com/) & [Bulma](http://bulma.io/).  
    Content licensed [CC BY‑NC‑SA 4.0](http://creativecommons.org/licenses/by-nc-sa/4.0/).
